import { Inter } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";


const InterFont = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${InterFont.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        
        <ToastContainer />
      </body>
    </html>
  );
}
